#!/bin/bash

declare -A DLV_PORT_MAP=(
  [kube-apiserver]=2341
  [kube-controller-manager]=2342
  [kube-scheduler]=2343
  [kube-proxy]=2344
  [kubelet]=2345
  [kubectl]=2346
)

if [ $# -lt 1 ]; then
    echo "Usage: $0 <kube_process_name>"
    exit 1
fi

program_name=$(basename $0)
if [[ $program_name == *dlv-attach* ]]; then
     process_name=$1
     pid=$(pidof $process_name)
     ${HOME}/kubernetes-binaries/dlv --listen=:${DLV_PORT_MAP[$process_name]} --headless=true --api-version=2 \
     --accept-multiclient attach $pid
      exit 0
fi

