#!/bin/bash

export LAUNCHPAD_ID=sombrafam
# Source folder for your juju code
export JUJU_SOURCE_FOLDER="/home/erlon/internal_git/juju"
export BASTION_IP="10.149.140.6"
# The controller name
export JUJU_CONTROLLER="juju36"
# The controller machine juju machine you want to debug
export DEBUG_TARGET_MACHINE="1"